### ISSUE TITLE
Timezone Translation

### ISSUE THREAD

**Issue by emath12** [YaleComputerSociety/ymeets#73]
Should be consumable in the person's local timezone, then stored in UTC, then pulled back down in their local timezone

**Comment by nickribs1** [comment]
https://ymeets.canny.io/admin/feedback/ymeets-feedback/p/12am-in-different-timezones

**Comment by rcheng11** [comment]
Timezone breaking when date ranges change as a result of the new time zone (usually happens when 12am is included in the time range)

**Comment by rcheng11** [comment]
Not a problem with timezone translation, but rather when the timezone translation affects the date ranges, breaking the calendar rendering
